version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: e-commerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: e_commerce_db
      POSTGRES_USER: e_commerce_user
      POSTGRES_PASSWORD: e_commerce_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../e_commerce-database/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U e_commerce_user -d e_commerce_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Session Storage
  redis:
    image: redis:7-alpine
    container_name: e-commerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # E-commerce GraphQL API
  e-commerce-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce-graphql-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      ECOMMERCE_DATABASE_HOST: postgres
      ECOMMERCE_DATABASE_PORT: 5432
      ECOMMERCE_DATABASE_NAME: e_commerce_db
      ECOMMERCE_DATABASE_USER: e_commerce_user
      ECOMMERCE_DATABASE_PASSWORD: e_commerce_password
      ECOMMERCE_DATABASE_SSL_MODE: disable
      
      # Redis Configuration
      ECOMMERCE_REDIS_ADDR: redis:6379
      ECOMMERCE_REDIS_PASSWORD: ""
      ECOMMERCE_REDIS_DB: 0
      
      # Server Configuration
      ECOMMERCE_SERVER_PORT: 8080
      ECOMMERCE_SERVER_ENABLE_PLAYGROUND: true
      
      # Authentication Configuration
      ECOMMERCE_AUTH_JWT_SECRET: your-jwt-secret-change-in-production
      ECOMMERCE_AUTH_TOKEN_EXPIRATION: 24h
      
      # CORS Configuration
      ECOMMERCE_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080"
      
      # Logging Configuration
      ECOMMERCE_LOG_LEVEL: info
      ECOMMERCE_LOG_FORMAT: json
      
      # Session Configuration
      ECOMMERCE_SESSION_SECRET: your-session-secret-change-in-production
      ECOMMERCE_SESSION_MAX_AGE: 24h
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: e-commerce-network
    driver: bridge
