#spring:
#  application:
#    name: e_commerce-service-endpoint-graphql
graphql:
  servlet:
    exception-handlers-enabled: true
    mapping: /graphql
    enabled: true
    tracing-enabled: true
    actuator-metrics: true
  tools:
    schema-location-pattern: "**/schema.graphqls"
    enabled: true
