spring:
  application:
    name: e_commerce-service-endpoint-graphql
  datasource:
    driver-class-name: org.postgresql.Driver
    username: e_commerce
    password: e_commerce
    url: jdbc:postgresql://localhost/e_commerce
graphql:
  servlet:
    exception-handlers-enabled: true
    mapping: /graphql
    enabled: true
    tracing-enabled: true
    actuator-metrics: true
  tools:
    schema-location-pattern: "**/schema.graphqls"
    enabled: true
